name:                haskell-todo
version:             0.1.0.0
github:              "FrankDeGroot/haskell-todo"
license:             BSD3
author:              "Frank de Groot - Schouten"
maintainer:          "fjtdg@hotmail.com"
copyright:           "Nope"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/FrankDeGroot/haskell-todo#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- temporary

library:
  source-dirs: src

executables:
  haskell-todo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - haskell-todo

tests:
  haskell-todo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - haskell-todo
    - HUnit
